name:          For Sale - 4 Spruce Court, Witless Bay, NL
description:   Gorgeous single family home located in the scenic town of Witless Bay, just 25-minutes from downtown St. John’s.
url:           http://4spruce.com/
image:         https://farm8.staticflickr.com/7778/17553342343_4434483510_z.jpg
email:         live@4spruce.com
phone:         1-709-747-9789

markdown:      rdiscount
permalink:     pretty
